# InterCity-Transport-System Configuration File
# version: v1.6

# The maximum amount of waiting time (in ticks) for player to join after receiving ICTS train.  (Default: 6000)
join-time-out: 6000

# Server List
# Format: Name/Data Server IP:Port
server-list:
  auto-servers:
    - MyServer/127.0.0.1:5000
  manual-servers:
    - MyManualServer/127.0.0.1:6000

# Whitelist
whitelist:
  enabled: false
  ip:
    - 127.0.0.1

# Blacklist
blacklist:
  enabled: false
  worlds:
    - survival1
    - survival2

# Keep all Intercity-Transport-System trains loaded (Default: true)
keep-chunks-loaded: true

# Customize your error messages here
messages:
  prefix: "&a[&eICTS&a]&r: "
  same-server: "&c&lError: &cCannot send players to the same server."
  blacklisted-world: "&c&lError: &cCannot send players to a blacklisted world."
  switch-server: "&bPlease connect to &a%server% &bto continue your journey."

# Enable Intra Server Train Sending (Default: false)
intra-server-train-sending: false

# Debug Mode (Warning: Spam Console)
debug: false