name: InterCity-Transport-System
version: ${project.version}
main: com.hasunemiku2015.icts.ICTS
api-version: 1.13
depend: [Train_Carts, BKCommonLib]
permissions:
  icts.buildsign:
    description: Allows a player to construct icts sign
    default: op
  icts.ictsinfo:
    description: Allows a player to check the ip and port of icts receving server
    default: op
#commands:
#  ictsinfo:
#    description: Checks the ip and port for icts receiving server
#    usage: /ictsinfo
#    permission: icts.ictsinfo